### ISSUE TITLE
Mod errors

### ISSUE THREAD

**Issue by Issues66010222** [Canthinkofaname/My-Uncivilized-Ponies#3] opened 2024-03-09 07:51 UTC
Keeping up with Unciv's scripting rules can be a hassle. I made a modified copy for myself, removing the Chrysalis stuff (and a lot of other things for personal reasons) just so I can have a playable version. I don't know how to fix the yellow warnings though.

Red:
My Uncivilized Ponies: (Unit) Queen Chrysalis?'s unique "Heal this unit by [-100] HP <upon gaining a [Queen Chrysalis] unit>" contains parameter -100, which does not fit parameter type positiveAmount !
My Uncivilized Ponies: (Unit) Queen Chrysalis?'s unique "Heal this unit by [-100] HP <upon founding a city>" contains parameter -100, which does not fit parameter type positiveAmount !
My Uncivilized Ponies: (Unit) Queen Chrysalis?'s unique "Heal this unit by [-100] HP <before [4] turns>" contains parameter -100, which does not fit parameter type positiveAmount !
My Uncivilized Ponies: (Unit) Queen Chrysalis?'s unique "Heal this unit by [-100] HP <during the [Ancient era]>" contains parameter -100, which does not fit parameter type positiveAmount !
Building Wonderbolt Academy. has greatPersonPoints for Great Engineer, which is not a unit in the ruleset!
My Uncivilized Ponies: (Unit) Queen Chrysalis?'s unique "Heal this unit by [-100] HP <upon gaining a [Queen Chrysalis] unit>" contains the conditional "upon gaining a [Queen Chrysalis] unit". This contains the parameter Queen Chrysalis which does not fit parameter type baseUnitFilter !

Yellow:
My Uncivilized Ponies: (Unit) Great Alicorn's unique "[-15]% Strength <vs [MagicGunpowder] units>" contains the conditional "vs [MagicGunpowder] units". This contains the parameter MagicGunpowder which does not fit parameter type mapUnitFilter !
My Uncivilized Ponies: (Unit) Great Alicorn's unique "Can instantly construct a [Citadel] improvement <by consuming this unit>" contains parameter Citadel, which does not fit parameter type improvementFilter !
My Uncivilized Ponies: (Unit) Stallioneer's unique "[+10]% Strength <when fighting in [Tundra] tiles>" contains the conditional "when fighting in [Tundra] tiles". This contains the parameter Tundra which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Stallioneer's unique "[+18]% Strength <when fighting in [Farm] tiles>" contains the conditional "when fighting in [Farm] tiles". This contains the parameter Farm which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Tundra Bear's unique "[+8]% Strength <when fighting in [Tundra] tiles>" contains the conditional "when fighting in [Tundra] tiles". This contains the parameter Tundra which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Arctic Killer's unique "[+12]% Strength <when fighting in [Snow] tiles>" contains the conditional "when fighting in [Snow] tiles". This contains the parameter Snow which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Arctic Killer's unique "[+8]% Strength <when fighting in [Tundra] tiles>" contains the conditional "when fighting in [Tundra] tiles". This contains the parameter Tundra which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Farmer Militia's unique "[+10]% Strength <when fighting in [Farm] tiles>" contains the conditional "when fighting in [Farm] tiles". This contains the parameter Farm which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Revolutionary's unique "[+8]% Strength <when fighting in [Farm] tiles>" contains the conditional "when fighting in [Farm] tiles". This contains the parameter Farm which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Revolutionary's unique "[+10]% Strength <when fighting in [Tundra] tiles>" contains the conditional "when fighting in [Tundra] tiles". This contains the parameter Tundra which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Revolutionary's unique "Invisible to non-adjacent units <in [Farm] tiles>" contains the conditional "in [Farm] tiles". This contains the parameter Farm which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Revolutionary's unique "[-10]% Strength <when fighting in [Hill] tiles>" contains the conditional "when fighting in [Hill] tiles". This contains the parameter Hill which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Rolling Giant's unique "[-10]% Strength <when fighting in [Hill] tiles>" contains the conditional "when fighting in [Hill] tiles". This contains the parameter Hill which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Changeling's unique "[+10]% Strength <when fighting in [Forest] tiles>" contains the conditional "when fighting in [Forest] tiles". This contains the parameter Forest which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Zebra's unique "[+5]% Strength <when fighting in [Jungle] tiles>" contains the conditional "when fighting in [Jungle] tiles". This contains the parameter Jungle which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Snowpony's unique "[+10]% Strength <when fighting in [Tundra] tiles>" contains the conditional "when fighting in [Tundra] tiles". This contains the parameter Tundra which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Snowpony's unique "[+10]% Strength <when fighting in [Snow] tiles>" contains the conditional "when fighting in [Snow] tiles". This contains the parameter Snow which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Unit) Animal Manipulator's unique "Can build [Forest] improvements on tiles" contains parameter Forest, which does not fit parameter type improvementFilter or terrainFilter !
My Uncivilized Ponies: (Unit) Animal Manipulator's unique "Double movement in [Forest]" contains parameter Forest, which does not fit parameter type terrainFilter !
My Uncivilized Ponies: (Unit) Sharpshooter's unique "Double movement in [Jungle]" contains parameter Jungle, which does not fit parameter type terrainFilter !
My Uncivilized Ponies: (Unit) Griff Piker's unique "[+50]% Strength <vs [Mounted] units>" contains the conditional "vs [Mounted] units". This contains the parameter Mounted which does not fit parameter type mapUnitFilter !
My Uncivilized Ponies: (Unit) Pikeman's unique "[+50]% Strength <vs [Mounted] units>" contains the conditional "vs [Mounted] units". This contains the parameter Mounted which does not fit parameter type mapUnitFilter !
My Uncivilized Ponies: (Unit) Quick Hitter's unique "[+100]% Strength <vs [Bomber] units>" contains the conditional "vs [Bomber] units". This contains the parameter Bomber which does not fit parameter type mapUnitFilter !
My Uncivilized Ponies: (Unit) Quick Hitter's unique "[+100]% Strength <vs [Helicopter] units>" contains the conditional "vs [Helicopter] units". This contains the parameter Helicopter which does not fit parameter type mapUnitFilter !
My Uncivilized Ponies: (Building) Lunar Panels's unique "Must be next to [Plains]" contains parameter Plains, which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Building) Lunar Panels's unique "Only available <in cities without a [Nuclear Plant]>" contains the conditional "in cities without a [Nuclear Plant]". This contains the parameter Nuclear Plant which does not fit parameter type buildingFilter !
My Uncivilized Ponies: (Building) Orchard's unique "[+2 Food] from [Citrus] tiles [in this city]" contains parameter Citrus, which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Building) Orchard's unique "[+2 Food] from [Cotton] tiles [in this city]" contains parameter Cotton, which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Building) Orchard's unique "[+2 Food] from [Sugar] tiles [in this city]" contains parameter Sugar, which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Building) Stalliongrad Tank Factories's unique "[+15]% Production when constructing [Armored] units [in all cities]" contains parameter Armored, which does not fit parameter type baseUnitFilter !
My Uncivilized Ponies: (Building) Stalliongrad Tank Factories's unique "[-20]% maintenance costs <for [Armored] units>" contains the conditional "for [Armored] units". This contains the parameter Armored which does not fit parameter type mapUnitFilter !
My Uncivilized Ponies: (Nation) Lunar Republic's unique "[+1 Faith] from every [Marsh]" contains parameter Marsh, which does not fit parameter type tileFilter or specialist or buildingFilter !
My Uncivilized Ponies: (Nation) Lunar Republic's unique "[+3 Faith] in cities on [Forest] tiles" contains parameter Forest, which does not fit parameter type terrainFilter !
My Uncivilized Ponies: (Nation) Aztlan's unique "[1] Movement <for [Land] units> <in [Jungle] tiles>" contains the conditional "in [Jungle] tiles". This contains the parameter Jungle which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Nation) Aztlan's unique "[+10]% Strength <for [Military] units> <when fighting in [Jungle] tiles>" contains the conditional "when fighting in [Jungle] tiles". This contains the parameter Jungle which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Nation) Aztlan's unique "[+30]% Strength <for [Land] units> <when defending> <in [Jungle] tiles>" contains the conditional "in [Jungle] tiles". This contains the parameter Jungle which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Nation) Aztlan's unique "[+10 Science] in cities on [Jungle] tiles" contains parameter Jungle, which does not fit parameter type terrainFilter !
My Uncivilized Ponies: (Nation) Aztlan's unique "[+5]% [Faith] from every [Jungle]" contains parameter Jungle, which does not fit parameter type tileFilter or buildingFilter !
My Uncivilized Ponies: (Nation) Appleloosa's unique "[+10]% Strength <for [Gunpowder] units> <when fighting in [Friendly] tiles>" contains the conditional "for [Gunpowder] units". This contains the parameter Gunpowder which does not fit parameter type mapUnitFilter !
My Uncivilized Ponies: (Nation) Changeling Lands's unique "[+8]% Strength <for [Military] units> <when fighting in [Forest] tiles> <hidden from users>" contains the conditional "when fighting in [Forest] tiles". This contains the parameter Forest which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Nation) Changeling Lands's unique "[+2]% [Production] from every [Forest] <when at war> <hidden from users>" contains parameter Forest, which does not fit parameter type tileFilter or buildingFilter !
My Uncivilized Ponies: (Nation) Stalliongrad's unique "[+1 Production] from every [Tundra]" contains parameter Tundra, which does not fit parameter type tileFilter or specialist or buildingFilter !
My Uncivilized Ponies: (Nation) Olenia's unique "[+12]% Strength <for [Sword] units> <before the [Renaissance era]>" contains the conditional "for [Sword] units". This contains the parameter Sword which does not fit parameter type mapUnitFilter !
My Uncivilized Ponies: (Nation) Olenia's unique "[+10]% Strength <for [Water] units> <when fighting in [Coast] tiles>" contains the conditional "when fighting in [Coast] tiles". This contains the parameter Coast which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Nation) Olenia's unique "[+1 Production, +1 Faith, +1 Culture] from every [Fishing Boats]" contains parameter Fishing Boats, which does not fit parameter type tileFilter or specialist or buildingFilter !
My Uncivilized Ponies: (Nation) Polar Bear Communities's unique "[+10]% Strength <for [Military] units> <when fighting in [Tundra] tiles>" contains the conditional "when fighting in [Tundra] tiles". This contains the parameter Tundra which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Nation) Polar Bear Communities's unique "[+15]% Strength <for [Military] units> <when fighting in [Snow] tiles>" contains the conditional "when fighting in [Snow] tiles". This contains the parameter Snow which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Nation) Polar Bear Communities's unique "[+3 Food, +1 Faith] from every [Snow]" contains parameter Snow, which does not fit parameter type tileFilter or specialist or buildingFilter !
My Uncivilized Ponies: (Nation) Polar Bear Communities's unique "[+1 Faith, +1 Gold] from every [Tundra]" contains parameter Tundra, which does not fit parameter type tileFilter or specialist or buildingFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Generated with weight [100] <in [Featureless] [Grassland] tiles>" contains the conditional "in [Featureless] [Grassland] tiles". This contains the parameter Grassland which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Generated with weight [100] <in [Featureless] [Plains] tiles>" contains the conditional "in [Featureless] [Plains] tiles". This contains the parameter Plains which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [10] <in [Grassland] [Hill] tiles> <in [Snow] [Hill] tiles> " contains the conditional "in [Grassland] [Hill] tiles". This contains the parameter Grassland which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [10] <in [Grassland] [Hill] tiles> <in [Snow] [Hill] tiles> " contains the conditional "in [Grassland] [Hill] tiles". This contains the parameter Hill which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [10] <in [Grassland] [Hill] tiles> <in [Snow] [Hill] tiles> " contains the conditional "in [Snow] [Hill] tiles". This contains the parameter Snow which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [10] <in [Grassland] [Hill] tiles> <in [Snow] [Hill] tiles> " contains the conditional "in [Snow] [Hill] tiles". This contains the parameter Hill which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [10] <in [Plains] [Hill] tiles> <in tiles without [Forest]> <in tiles without [Jungle]>" contains the conditional "in [Plains] [Hill] tiles". This contains the parameter Plains which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [10] <in [Plains] [Hill] tiles> <in tiles without [Forest]> <in tiles without [Jungle]>" contains the conditional "in [Plains] [Hill] tiles". This contains the parameter Hill which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [10] <in [Plains] [Hill] tiles> <in tiles without [Forest]> <in tiles without [Jungle]>" contains the conditional "in tiles without [Forest]". This contains the parameter Forest which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [10] <in [Plains] [Hill] tiles> <in tiles without [Forest]> <in tiles without [Jungle]>" contains the conditional "in tiles without [Jungle]". This contains the parameter Jungle which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [100] <in [Grassland] tiles>" contains the conditional "in [Grassland] tiles". This contains the parameter Grassland which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [20] <in [Grassland] tiles> <in tiles without [Fresh Water]>" contains the conditional "in [Grassland] tiles". This contains the parameter Grassland which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Magic Crystals's unique "Minor deposits generated with weight [30] <in [Plains] tiles>" contains the conditional "in [Plains] tiles". This contains the parameter Plains which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Apples's unique "Generated on every [7] tiles <in [Featureless] [Grassland] tiles>" contains the conditional "in [Featureless] [Grassland] tiles". This contains the parameter Grassland which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Apples's unique "Doesn't generate naturally <in [Tundra] tiles>" contains the conditional "in [Tundra] tiles". This contains the parameter Tundra which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Gems's unique "Doesn't generate naturally <in [Forest] tiles> <in tiles without [Hill]>" contains the conditional "in [Forest] tiles". This contains the parameter Forest which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Gems's unique "Doesn't generate naturally <in [Forest] tiles> <in tiles without [Hill]>" contains the conditional "in tiles without [Hill]". This contains the parameter Hill which does not fit parameter type tileFilter !
My Uncivilized Ponies: (Resource) Cod's unique "Generated on every [10] tiles <in [Featureless] [Coast] tiles> <in [Tundra] Regions>" contains the conditional "in [Featureless] [Coast] tiles". This contains the parameter Coast which does not fit parameter type tileFilter !

Green:
My Uncivilized Ponies: (Unit) Choose Your Leader's unique "Cannot move <for [Human player]>" contains a conditional on a unit movement unique. Due to performance considerations, this unique is cached on the unit, and the conditional may not always limit the unique correctly.
My Uncivilized Ponies: (Nation) Equestria's unique "Ponies" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Equestria's unique "Non-Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Lunar Republic's unique "Ponies" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Lunar Republic's unique "Non-Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Aztlan's unique "Ponies" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Aztlan's unique "Non-Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Nova Griffonia's unique "Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Nova Griffonia's unique "Non-Ponies" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Appleloosa's unique "Ponies" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Appleloosa's unique "Non-Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Changeling Lands's unique "Changelings" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Changeling Lands's unique "Non-Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Stalliongrad's unique "Ponies" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Stalliongrad's unique "Non-Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) The Crystal Empire's unique "Ponies" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) The Crystal Empire's unique "Non-Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Olenia's unique "Non-Ponies" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Olenia's unique "Non-Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Polar Bear Communities's unique "Non-Ponies" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Polar Bear Communities's unique "Arctic Nations" not found in Unciv's unique types, and is not used as a filtering unique.
My Uncivilized Ponies: (Nation) Polar Bear Communities's unique "Non-Griffonians" not found in Unciv's unique types, and is not used as a filtering unique.

**Comment by Huymnsel** [comment] 2024-03-09 08:25
"Heal this unit by [negative value]" is now replaced by "This Unit takes [] damage"

MagicGunpowder unit type does not exist in UnitTypes.json, consider adding it

If you know any automation method that can make this easier, let me know too!

**Comment by Issues66010222** [comment] 2024-03-12 02:08
Well, apparently most (if not all) of the yellow warnings are nothing at all, and the error checker is probably just broken. So all that was really needed to change was:
1. The Chrysalis stuff, also in UnitTypes.json.
2. The UnitType "MagicGunpowder" actually being misspelled as "GunpowderMagic" in UnitTypes.json.
3. The unique "**Only available** <for [Non-Ponies]>" replaced with "**Unavailable** <for [Ponies]>", same with "Only available <for [Non-Griffonians]>" (replace it with "Unavailable <for [Griffonians]>"); **_Non-Ponies_** and **_Non-Griffonians_** are redundant. (Unless I'm missing something here and there is a reason why they're there?)
The "does not fit parameter type" warnings might be outdated or not properly implement.

In terms of automation: I'm not sure if this helps, but I found this: [Type Checking](https://yairm210.github.io/Unciv/Modders/Type-checking/).

**Comment by Huymnsel** [comment] 2024-03-12 03:12
Correct, the yellow warnings should go away if you pick the correct base ruleset (God and Kings is the default)

For the  "does not fit parameter type" red warnings, they are caused by using `Heal this unit by [negative amount]` and must be replaced with `This Unit takes [positive amount] damage`

**Comment by Issues66010222** [comment] 2024-03-12 06:56
> Correct, the yellow warnings should go away if you **pick the correct base ruleset** (God and Kings is the default)

Oh yeah, I forgot about that! (I also forgot about the `code` texting, silly me.)
BTW I was referring to the yellow warnings when I mentioned the "does not fit parameter type" warnings, I should've specified "Filter" warnings (which were only there because I didn't set the error checker to G&K).

This should be the fixed version, I guess: 
[My Uncivilized Ponies (fixed).zip](https://github.com/Canthinkofaname/My-Uncivilized-Ponies/files/14568250/My.Uncivilized.Ponies.fixed.zip)
That's just the JSONs I changed; that should be all of them, I think. I also added the Unique `"Only available <for [Ponies]>"` to all the _Magic_ units that were missing this; also, I noticed these units were set to the default Unit Types (e.g. _Magical Rifleman_ is a `Gunpowder` type instead of `MagicGunpowder`), though I left them as is because I don't know what would happen if I changed that.

**Comment by Canthinkofaname** [comment] 2024-03-13 20:24
You can remove MagicGunpowder. It's basically useless. I was going for being able to pick leaders like in civ 6 with the Chrysalis stuff but that didn't work out. You can make a pull request if you wanna see this in the main mod if you really want to. Or I can just make you a contributor. I have a backup incase anything happens. Sorry for not updating the mod as recently. Schools been getting in the way and I can only mod through my phone after my chrome book broke. I would gladly accept help! Also, is there anything that you want added to the mod?  Ill try to add it, Although don't count on it being added as the state of the mod shows how unreliable I am

**Comment by Canthinkofaname** [comment] 2024-03-13 21:03
Alright, I updated the mod so that all of those problems should be fixed.

**Comment by Canthinkofaname** [comment] 2024-03-15 19:23
I forgot to mention, the reason I didn't fully copy and paste the files from your .zip, because the mod is based off of the EAW HOI4 mod, which allows every species to use magical weapons through the use of magical crystals , or something along the lines of that, so thats why every nation, and not just pony nations can use magical units.

I mainly tested this using only the mod's nations, but I might try to make the mod make a bit more sense even if your using base game nations 

Unfortunately it looks like my android is too old to actually use android studio, but I'll try to buy a newer phone...probably isn't going to happen in the near future though 😅 

Is there anything else you'd like me to address? If not, you can just close the issue.

**Comment by Issues66010222** [comment] 2024-03-16 13:59
> allows every species to use magical weapons through the use of magical crystals

I knew that. I don't remember if I added the `Only available for Ponies` on other units where there shouldn't, but I'm pretty sure most of what I did was replaced the `Only available with Non-X` with `Unavailable with X`.

Well, that's it, then.

**Closed** 2024-03-16 14:00 UTC
